apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: androidmaster-de-tls
spec:
  secretName: androidmaster
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: androidmaster.de
  dnsNames:
    - androidmaster.de
    - www.androidmaster.de
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - androidmaster.de
          - www.androidmaster.de